name: build

on:
  workflow_dispatch: 
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'action.yml'
      - 'dist/**'
      - '.github/**'

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"

    - name: Attach HEAD
      run: git checkout master

    - name: build
      run: |
        npm i
        npm i -g @vercel/ncc
        npm run build
      
    - name: Push if needed
      run: |
        git diff --exit-code || (git add . && git commit -m "BY-CI" && git push origin HEAD)
